import Link from "next/link";
import { ArrowRight, BrainCircuit, Cpu, Eye, Globe2, HeartHandshake, Languages, Lightbulb, Rocket, Target, Users } from "lucide-react";
import { SiteShell } from "@/components/site/SunshotShell";

const specs = [["48B", "Total parameters"], ["~12B", "Active per token"], ["56", "Transformer layers"], ["8 / 2", "Experts / active"], ["128K", "Native context"], ["256K", "Experimental context"], ["64 / 8", "Attention / KV heads"], ["160K", "Vocabulary target"]];
const benchmarks = [["GDPVal-AA v2", "1203 Elo"], ["MMLU-Pro", "79.4%"], ["LegalBench", "86.2%"], ["HumanEval+", "84.1%"], ["Bangla Reasoning", "88.6%"], ["Source-Grounded QA", "91.3%"]];

export default function AboutPage() {
  return <SiteShell><section className="inner-hero about-hero"><div className="page-width inner-hero-grid"><div><div className="micro-label"><i /> ABOUT SUNSHOT AI</div><p className="spaced">PEOPLE · PURPOSE · A BRIGHTER TOMORROW</p><h1>Building A Smarter<br />Future From <em>Bangladesh</em></h1><p>Sunshot AI is an upcoming intelligent AI platform from Bangladesh, built to create inclusive, multilingual, human-centered AI for a global future.</p><div className="button-row"><Link className="gold-button" href="/launch#waitlist">Join Our Journey <ArrowRight /></Link><Link className="dark-button" href="#story">Our Story</Link></div><div className="hero-facts"><span><BrainCircuit />Bangladesh<br />Born Innovation</span><span><Globe2 />Global<br />Ambition</span><span><Users />AI for<br />Everyone</span></div></div><div className="about-hero-art"><img src="/neural-earth.jpg" alt="Bangladesh-born global AI network" /><div className="about-emblem"><img src="/sunshot-logo.jpg" alt="Sunshot AI emblem" /></div></div></div></section>

  <section className="content-section"><div className="page-width"><div className="section-cap"><span>WHO WE ARE</span><i /></div><div className="who-grid"><div><h2>More Than <em>AI</em><br /><span>A Movement for a Brighter Tomorrow</span></h2><p>Sunshot AI is a next-generation intelligent AI platform from Bangladesh, created to push the boundaries of what’s possible with AI. We believe intelligence should be inclusive, accessible, and human-centered. Our mission is to empower people, unlock ideas, and solve real-world problems through advanced, multilingual, and culturally aware AI.</p></div><div className="bangladesh-panel"><strong>BANGLADESHI IDEAS</strong><span>GLOBAL POSSIBILITIES</span><p>Local talent. Global impact.<br />Real solutions. Lasting change.</p></div></div><div className="mission-grid"><article><Target /><div><span>OUR MISSION</span><h3>To make AI more intelligent, inclusive, and useful for real people.</h3><p>AI that understands people, adapts to cultures and languages, and creates meaningful everyday impact.</p></div></article><article><Eye /><div><span>OUR VISION</span><h3>To create a Bangladesh-born AI ecosystem that contributes to the world.</h3><p>Innovation from Bangladesh helping shape a more intelligent, inclusive and connected future.</p></div></article></div></div></section>

  <section className="content-section alt"><div className="page-width"><div className="section-cap"><span>CORE ARCHITECTURE</span><i /></div><div className="section-intro"><div><h2>Hybrid MoE Intelligence.<br /><em>Built for efficient reasoning.</em></h2><p>Concept specification for the current development target.</p></div><div className="compute-chip"><Cpu /><strong>2× NVIDIA H100 SXM 80GB</strong><span>160 GB HBM3 · BF16 / FP8 · ~1.9 PFLOPS-class</span></div></div><div className="spec-grid">{specs.map(([value,label]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><div className="architecture-note"><BrainCircuit /><p>Hybrid Mixture-of-Experts Transformer · Grouped Query Attention · Global/Sliding Attention · SwiGLU · Extended RoPE · Custom multilingual BPE · 0.6–1.8s target time to first token · 75–140 tokens/sec target generation speed.</p></div></div></section>

  <section className="content-section"><div className="page-width"><div className="section-cap"><span>BENCHMARK PROFILE</span><i /></div><div className="benchmark-panel"><div className="elo-spotlight"><span>GDPVal-AA v2</span><strong>1203<small>Elo</small></strong><p>Internal evaluation profile</p></div><div className="benchmark-list">{benchmarks.map(([name,value]) => <div key={name}><span>{name}</span><strong>{value}</strong><i style={{width: name === "GDPVal-AA v2" ? "96%" : value}} /></div>)}</div></div><p className="disclosure">Internal development-stage figures and experimental benchmark targets. Independent testing and reproducibility are planned before final product claims.</p></div></section>

  <section className="content-section story-section" id="story"><div className="page-width"><div className="section-cap"><span>THE SUNSHOT MAKING</span><i /></div><div className="story-grid"><div className="story-logo"><img src="/sunshot-logo.jpg" alt="Sunshot AI" /></div><div><h2>From a practical question<br />to a <em>global ambition.</em></h2><p>Sunshot AI began with a simple question: could an AI system created from Bangladesh understand people more naturally while remaining useful, responsible, and globally competitive? Md. Nahid Alom’s earlier work on LexGlobal BD exposed the need for clearer legal information, multilingual communication, reliable research, and intelligent routing. That experience became the foundation for a broader AI concept. Months of research followed—covering mixture-of-experts architecture, retrieval, legal reasoning, multimodal tools, privacy, cost efficiency, and Bangla-first interaction. The project gradually evolved from an experimental idea into a complete product direction: a human-centered platform able to support conversation, research, coding, visual creation, data analysis, and specialized legal intelligence. Sunshot AI is still in its prelaunch stage, and every architecture choice, benchmark target, and feature will continue to be tested. Its ambition, however, is already clear: build meaningful intelligence in Bangladesh and make it useful to the world.</p></div></div></div></section>

  <section className="values-band"><div className="page-width"><div className="section-cap"><span>WHAT DRIVES US FORWARD</span><i /></div><div className="value-grid">{[{i:HeartHandshake,t:"Human-Centered Design",d:"We build AI for people—real needs, real lives, real impact."},{i:Languages,t:"Multilingual Intelligence",d:"We celebrate every language, culture and voice."},{i:Lightbulb,t:"Advanced Reasoning",d:"Deeper, more meaningful intelligence for complex work."},{i:Rocket,t:"Built in Bangladesh, for the World",d:"Local purpose with global ambition."}].map(({i:Icon,t,d}) => <article key={t}><Icon /><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section></SiteShell>;
}
