import Link from "next/link";
import { ArrowRight, BarChart3, Bot, Braces, BrainCircuit, Code2, Database, FileText, Globe2, ImagePlus, Languages, LockKeyhole, SearchCheck, ShieldCheck, Sparkles, UserRoundCog } from "lucide-react";
import { SiteShell } from "@/components/site/SunshotShell";

const features = [
  {n:"01",i:BrainCircuit,t:"Advanced AI Chat",s:"Multi-model intelligence for real conversations",d:"Instant answers, deep reasoning, problem solving and creative work with context-aware responses.",tags:["Fast","Accurate","Context-Aware"]},
  {n:"02",i:SearchCheck,t:"Deep Research AI",s:"In-depth insights with real-world context",d:"Source-aware research with hybrid retrieval, reranking, verification and citation-ready summaries.",tags:["Source-Backed","Multi-Perspective","Long-Form"]},
  {n:"03",i:Sparkles,t:"Content Creation Suite",s:"Turn ideas into powerful content",d:"Create high-quality text, visual concepts, presentations and structured content using AI-powered tools.",tags:["Text","Images","Presentations"]},
  {n:"04",i:Languages,t:"Multilingual Intelligence",s:"Break language barriers",d:"Native Bangla and English, natural Banglish, multilingual generation and culturally aware understanding.",tags:["24+ Site Languages","Bangla-First","Cultural Context"]},
  {n:"05",i:Code2,t:"Coding & Development",s:"Build ideas faster",d:"Code generation, debugging, conversion, explanation, unit testing and API-development assistance.",tags:["Code Generation","Debugging","Multiple Languages"]},
  {n:"06",i:BarChart3,t:"Data Analysis & Visualization",s:"Turn data into decisions",d:"Understand CSV and JSON, analyze patterns, solve mathematical problems and produce structured insights.",tags:["Data Analysis","Charts","Clear Insights"]},
  {n:"07",i:ImagePlus,t:"Image & Media Tools",s:"Create, understand, transform",d:"Image understanding, screenshot analysis, visual question answering and planned AI image generation.",tags:["Image Generation","Vision","Creative Design"]},
  {n:"08",i:FileText,t:"Document Assistant",s:"Summarize, analyze, create",d:"Work with PDFs and documents, extract key information, analyze structure and prepare clear summaries.",tags:["PDF Support","Summarization","Documents"]},
  {n:"09",i:UserRoundCog,t:"Personalized AI Experience",s:"Your AI, your way",d:"Personal preferences, saved context, adjustable reasoning modes and tailored responses for your goals.",tags:["Custom Settings","Reasoning Modes","Personalized"]},
  {n:"10",i:LockKeyhole,t:"Secure & Private",s:"Your data, your control",d:"TLS transmission, encrypted storage, temporary processing, sensitive-document isolation and training opt-out plans.",tags:["Encrypted","Private","User Control"]},
  {n:"11",i:ShieldCheck,t:"Specialized Legal Intelligence",s:"Jurisdiction-aware understanding",d:"Legal retrieval, source citations, cross-jurisdiction context, legal reasoning and confidence gating.",tags:["Legal Search","Jurisdictions","Confidence Gate"]},
  {n:"12",i:Database,t:"Developer API Ecosystem",s:"Build with Sunshot intelligence",d:"Planned chat, responses, embeddings, image, research and legal-search endpoints with streaming and tool calling.",tags:["Streaming","Structured JSON","Tool Calling"]},
];

export default function FeaturesPage(){return <SiteShell><section className="inner-hero features-hero"><div className="page-width feature-hero-grid"><div><div className="micro-label"><i /> FEATURES</div><p className="spaced">POWERED BY NEXT-GEN AI</p><h1>Powerful <em>Features</em></h1><h2>Everything you need for a smarter, more productive tomorrow.</h2><p>Sunshot AI combines advanced models, real-world understanding, human-centered design and specialized legal intelligence for learning, creating, research and complex problem solving—all in one platform.</p></div><div className="feature-hero-art"><img className="robot-art" src="/sunshotaiprelaunch/sunshot-robot.jpg" alt="Sunshot AI assistant robot" /><img className="mini-logo" src="/sunshotaiprelaunch/sunshot-logo.jpg" alt="Sunshot AI" /></div></div></section><section className="content-section feature-content"><div className="page-width"><div className="category-pills"><span>All Features</span><span>AI Models</span><span>Research & Learning</span><span>Creativity</span><span>Productivity</span><span>Global Access</span><span>Security</span></div><div className="feature-card-grid">{features.map(({n,i:Icon,t,s,d,tags})=><article key={n}><div className="feature-card-head"><span>{n}</span><Icon /></div><h3>{t}</h3><h4>{s}</h4><p>{d}</p><div>{tags.map(tag=><span key={tag}>{tag}</span>)}</div></article>)}</div><div className="coming-panel"><Bot /><div><h2>More Features <em>Coming Soon</em></h2><p>Voice assistance, AI agents, advanced workflows, enterprise tools and much more are on the roadmap.</p></div><Link className="gold-button" href="/launch#waitlist">Join Waitlist <ArrowRight /></Link></div><div className="feature-stats"><span><Braces /><strong>12+</strong>Core capabilities</span><span><Globe2 /><strong>24</strong>Website languages</span><span><Bot /><strong>24/7</strong>AI assistance</span><span><Globe2 /><strong>Global</strong>Access vision</span></div></div></section></SiteShell>}
